language: none

matrix:
  include:
    - os: linux
      dist: cosmic
      compiler: clang
      env: CXX=clang++-3.8 CC=clang-3.8
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
          packages:
            - clang-3.8
              # VERY IMPORTANT TO INSTALL g++-5! clang doesn't come with a standard library, so
              # we need to install g++-5 for a C++14 standard library.
            - g++-5

    - os: linux
      dist: cosmic
      compiler: gcc
      env: CXX=g++-5 CC=gcc-5 QT=5
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5

install:
before_install:
 - sudo apt-get update -qq ; fi
 - sudo apt-get install build-essential libgl1-mesa-dev ; fi
 - sudo apt-get -yy install qtbase5-dev qt5-qmake; fi

script:
 - qmake -v #shows version
 - qmake Monarch-Connect.pro
 - make
