language: generic
dist: xenial

matrix:
  include:
    - compiler: clang
      env: CXX=clang++-3.8 CC=clang-3.8
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
          packages:
            - clang-3.8
              # VERY IMPORTANT TO INSTALL g++-5! clang doesn't come with a standard library, so
              # we need to install g++-5 for a C++14 standard library.
            - g++-5

    - compiler: gcc
      env: CXX=g++-5 CC=gcc-5 QT=5
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5

install:
before_install:
 - sudo apt-get update -qq
 - sudo apt-get -yy install build-essential mesa-common-dev libgl1-mesa-dev libglu1-mesa-dev
 - sudo apt-get -yy install qtbase5-dev libqt5opengl5 qt5-qmake

script:
 - qmake -qt=qt5 -v #shows version
 - qmake -qt=qt5 Monarch-Connect-Parent.pro
 - make
